#
# Module Manifest for Modules.Winget.Update
#
# Generated by V1ola1ne
#
# Generated on 12.07.2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = "Modules.Winget.Update.psm1"

    # Author of this module
    Author = 'V1ola1ne'

    GUID = '144ed39a-e67a-4451-991e-92ecfd723012'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Description of the functionality provided by this module
    Description = '
    This provides a way, to use winget to update all winget packages in one go
    more information at https://github.com/V1ola1ne/Package-Updater/wiki
    '

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Install-PackageUpdates')

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    AliasesToExport = @()

    # Modules Required to Work
    RequiredModules = @()


    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/V1ola1ne/Package-Updater'
            
            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/V1ola1ne/Package-Updater/releases'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # A URL to get more information about this module
    HelpInfoURI = 'https://github.com/V1ola1ne/Package-Updater/wiki'

}